### ISSUE TITLE
ModuleNotFoundError: No module named 'idr'

### ISSUE THREAD

**Issue by ramnageena11** [NICHD-BSPC/termseq-peaks#2]
Hi,
Got an error while ran the script for calling the peaks.

$ termseq_peaks /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode07.plus.bedgraph /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode08.plus.bedgraph /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode09.plus.bedgraph --peaks /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode789.plus.peaks --strand +
Traceback (most recent call last):
  File "/home/majorram/anaconda3/bin/termseq_peaks", line 11, in <module>
    from peaklib.peaklib import idr_peak_calls
  File "/home/majorram/anaconda3/lib/python3.9/site-packages/peaklib/peaklib.py", line 6, in <module>
    from idr import idr
ModuleNotFoundError: No module named 'idr'

**Comment by ramnageena11** [comment]
Hi,
Could you please look into this?

**Comment by daler** [comment]
Yes -- we see the issue and will address it as soon as we can.

**Comment by ramnageena11** [comment]
Thanks

**Comment by daler** [comment]
If you use the `assign_class` branch (see #1) this has the fixes. We still need to update the docs and add tests for the new annotation scripts, but you can try those too and your feedback would be welcome.

**Comment by daler** [comment]
@ramnageena11 this is now merged in to the master branch, so you should be good to go.

**Comment by daler** [comment]
By the way, please see the new installation instructions in the README -- since recent versions of `idr` are only available on the conda channel, installation must be via conda.
