### ISSUE TITLE
Wrong IDR being installed

### ISSUE THREAD

**Issue by Gr1m3y** [NICHD-BSPC/termseq-peaks#5]
Hi, 

I am just making a note here to say that there seems to be an issue with installing the correct `idr` package. Here are the steps I initially took to install the program:

```
conda create -n termseq-peaks python=3.10
conda activate termseq-peaks
python -m pip install git+https://github.com/NICHD-BSPC/termseq-peaks
```

After this, I kept getting the error that idr was missing. I eventually realised that pip was installing a different idr than the one needed. I was able to fix the issue as follows:

```
pip uninstall idr
conda install idr
```

Hopefully this note is helpful to you! Took me some time to realise what the issue was. 

Cheers!

**Comment by esnaultc** [comment]
Hi @Gr1m3y,

Thanks for figuring out the ``idr`` work-around!

It is a known issue with ``pip`` and we recommend installing with ``conda``, but ``conda`` might not always be possible so it is great to have instructions.

We added a note about this in the [installation instructions](https://github.com/NICHD-BSPC/termseq-peaks#installation).

Thanks
